import Head from "next/head";
import { Button } from "@mui/material";
import Link from "next/link";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/">Go To Home</Link>
      </main>

      <footer></footer>
    </div>
  );
}
